#!/usr/local/bin/zsh
set -ex

rm -rf lib
tsc

if [[ $1 == 'server_ext' ]];then
  pip install -e .
fi

jlpm build
jupyter lab build

if [[ $1 == 'run' ]];then
  jupyter lab --NotebookApp.iopub_data_rate_limit=10000000
fi

